In [ ]:
# keywords

# Titanic, apply, pd.query, np.where, KNeighborsClassifier, GaussianNB, DecisionTreeClassifier
# LogisticRegression, confusion_matrix, precision_score, recall_score

# Урок 1. Метрики качества классификации ч.1

В уроке мы разбирали матрицу ошибок и некоторые метрики, основанные на терминах матрицы ошибок. Здесь же посмотрим, как эти метрики применять на практике и что  по ним можно выяснить.

### 1.1
Выкачайте тренировочный датасет Titanic - train.csv - с сайта [kaggle](https://www.kaggle.com/c/titanic/data). С помощью функции pd.read_csv() загрузите данные в датафрейм. Выведите первые 20 строк и проанализируйте данные: какие колонки присутствуют (более конкретная информация по ним есть на сайте kaggle), каким образом в них обозначены данные и какие типы данных используются (используйте pandas.dtypes). **

In [1]:
import pandas as pd

In [2]:
### YOUR CODE HERE ###

start_df = pd.read_csv('./data/titanic-train.csv')
start_df.head(20)

PassengerId  Survived  Pclass  \
0             1         0       3   
1             2         1       1   
2             3         1       3   
3             4         1       1   
4             5         0       3   
5             6         0       3   
6             7         0       1   
7             8         0       3   
8             9         1       3   
9            10         1       2   
10           11         1       3   
11           12         1       1   
12           13         0       3   
13           14         0       3   
14           15         0       3   
15           16         1       2   
16           17         0       3   
17           18         1       2   
18           19         0       3   
19           20         1       3   

                                                 Name     Sex   Age  SibSp  \
0                             Braund, Mr. Owen Harris    male  22.0      1   
1   Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                              Heikkinen, Miss. Laina  female  26.0      0   
3        Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                            Allen, Mr. William Henry    male  35.0      0   
5                                    Moran, Mr. James    male   NaN      0   
6                             McCarthy, Mr. Timothy J    male  54.0      0   
7                      Palsson, Master. Gosta Leonard    male   2.0      3   
8   Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  female  27.0      0   
9                 Nasser, Mrs. Nicholas (Adele Achem)  female  14.0      1   
10                    Sandstrom, Miss. Marguerite Rut  female   4.0      1   
11                           Bonnell, Miss. Elizabeth  female  58.0      0   
12                     Saundercock, Mr. William Henry    male  20.0      0   
13                        Andersson, Mr. Anders Johan    male  39.0      1   
14               Vestrom, Miss. Hulda Amanda Adolfina  female  14.0      0   
15                   Hewlett, Mrs. (Mary D Kingcome)   female  55.0      0   
16                               Rice, Master. Eugene    male   2.0      4   
17                       Williams, Mr. Charles Eugene    male   NaN      0   
18  Vander Planke, Mrs. Julius (Emelia Maria Vande...  female  31.0      1   
19                            Masselmani, Mrs. Fatima  female   NaN      0   

    Parch            Ticket     Fare Cabin Embarked  
0       0         A/5 21171   7.2500   NaN        S  
1       0          PC 17599  71.2833   C85        C  
2       0  STON/O2. 3101282   7.9250   NaN        S  
3       0            113803  53.1000  C123        S  
4       0            373450   8.0500   NaN        S  
5       0            330877   8.4583   NaN        Q  
6       0             17463  51.8625   E46        S  
7       1            349909  21.0750   NaN        S  
8       2            347742  11.1333   NaN        S  
9       0            237736  30.0708   NaN        C  
10      1           PP 9549  16.7000    G6        S  
11      0            113783  26.5500  C103        S  
12      0         A/5. 2151   8.0500   NaN        S  
13      5            347082  31.2750   NaN        S  
14      0            350406   7.8542   NaN        S  
15      0            248706  16.0000   NaN        S  
16      1            382652  29.1250   NaN        Q  
17      0            244373  13.0000   NaN        S  
18      0            345763  18.0000   NaN        S  
19      0              2649   7.2250   NaN        C

In [3]:
start_df.dtypes

PassengerId      int64
Survived         int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Cabin           object
Embarked        object
dtype: object

### 1.2
Проверьте, имеются ли пропущенные значения в колонках, и выведите сумму всех пропущенных значений в каждой из колонок.

In [4]:
### YOUR CODE HERE ###

start_df.isna().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

### 1.3
Замените все пропущенные значения колонки Age на медианы в зависимости от пола человека: т.е. если пол человека в строке с пропущенным значением "male", заменяете пропущенное значение возраста на медиану по всем известным возрастам мужчин, и наоборот. Выведите медианы возраста в зависимости от пола. Пропущенные значения колонок Cabin и Embarked замените на U (Unknown).

Примечание: для группировки по полу можно использовать метод df.groupby(), который имеет встроенные агрегатные функции (в т.ч. для вычисления медианы).  Для установки пропущенных значений в датасете воспользуйтесь функцией df.apply().

In [5]:
### YOUR CODE HERE ###

start_df.groupby('Sex').median()

PassengerId  Survived  Pclass   Age  SibSp  Parch  Fare
Sex                                                            
female        414.5       1.0     2.0  27.0    0.0    0.0  23.0
male          464.0       0.0     3.0  29.0    0.0    0.0  10.5

In [6]:
start_df.groupby('Survived').count()

PassengerId  Pclass  Name  Sex  Age  SibSp  Parch  Ticket  Fare  \
Survived                                                                    
0                 549     549   549  549  424    549    549     549   549   
1                 342     342   342  342  290    342    342     342   342   

          Cabin  Embarked  
Survived                   
0            68       549  
1           136       340

In [7]:
def fill_average_1(pd_obj):
    age = pd_obj['Age']
    sex = pd_obj['Sex']
    if age != age:
        if sex == 'female':
            return 27
        elif sex == 'male':
            return 29
    else:
        return age

In [8]:
start_df['Age'] = start_df.apply(fill_average_1, axis = 1)

In [9]:
start_df.head(20)

PassengerId  Survived  Pclass  \
0             1         0       3   
1             2         1       1   
2             3         1       3   
3             4         1       1   
4             5         0       3   
5             6         0       3   
6             7         0       1   
7             8         0       3   
8             9         1       3   
9            10         1       2   
10           11         1       3   
11           12         1       1   
12           13         0       3   
13           14         0       3   
14           15         0       3   
15           16         1       2   
16           17         0       3   
17           18         1       2   
18           19         0       3   
19           20         1       3   

                                                 Name     Sex   Age  SibSp  \
0                             Braund, Mr. Owen Harris    male  22.0      1   
1   Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                              Heikkinen, Miss. Laina  female  26.0      0   
3        Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                            Allen, Mr. William Henry    male  35.0      0   
5                                    Moran, Mr. James    male  29.0      0   
6                             McCarthy, Mr. Timothy J    male  54.0      0   
7                      Palsson, Master. Gosta Leonard    male   2.0      3   
8   Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  female  27.0      0   
9                 Nasser, Mrs. Nicholas (Adele Achem)  female  14.0      1   
10                    Sandstrom, Miss. Marguerite Rut  female   4.0      1   
11                           Bonnell, Miss. Elizabeth  female  58.0      0   
12                     Saundercock, Mr. William Henry    male  20.0      0   
13                        Andersson, Mr. Anders Johan    male  39.0      1   
14               Vestrom, Miss. Hulda Amanda Adolfina  female  14.0      0   
15                   Hewlett, Mrs. (Mary D Kingcome)   female  55.0      0   
16                               Rice, Master. Eugene    male   2.0      4   
17                       Williams, Mr. Charles Eugene    male  29.0      0   
18  Vander Planke, Mrs. Julius (Emelia Maria Vande...  female  31.0      1   
19                            Masselmani, Mrs. Fatima  female  27.0      0   

    Parch            Ticket     Fare Cabin Embarked  
0       0         A/5 21171   7.2500   NaN        S  
1       0          PC 17599  71.2833   C85        C  
2       0  STON/O2. 3101282   7.9250   NaN        S  
3       0            113803  53.1000  C123        S  
4       0            373450   8.0500   NaN        S  
5       0            330877   8.4583   NaN        Q  
6       0             17463  51.8625   E46        S  
7       1            349909  21.0750   NaN        S  
8       2            347742  11.1333   NaN        S  
9       0            237736  30.0708   NaN        C  
10      1           PP 9549  16.7000    G6        S  
11      0            113783  26.5500  C103        S  
12      0         A/5. 2151   8.0500   NaN        S  
13      5            347082  31.2750   NaN        S  
14      0            350406   7.8542   NaN        S  
15      0            248706  16.0000   NaN        S  
16      1            382652  29.1250   NaN        Q  
17      0            244373  13.0000   NaN        S  
18      0            345763  18.0000   NaN        S  
19      0              2649   7.2250   NaN        C

### 1.4
Выведите возраст пассажиров с PassengerID = [6, 20]. Убедитесь, что заполнены все пропущенные значения (воспользуйтесь функцией df.isnull() ).

In [10]:
### YOUR CODE HERE ###

start_df[(start_df.index == 6) | (start_df.index == 20)]['Age']

6     54.0
20    35.0
Name: Age, dtype: float64

In [11]:
# start_df[start_df.index.isin([6,20])]
start_df.query("index in (6,20)")

PassengerId  Survived  Pclass                     Name   Sex   Age  SibSp  \
6             7         0       1  McCarthy, Mr. Timothy J  male  54.0      0   
20           21         0       2     Fynney, Mr. Joseph J  male  35.0      0   

    Parch  Ticket     Fare Cabin Embarked  
6       0   17463  51.8625   E46        S  
20      0  239865  26.0000   NaN        S

In [12]:
start_df[start_df.Age.isnull() == True]

Empty DataFrame
Columns: [PassengerId, Survived, Pclass, Name, Sex, Age, SibSp, Parch, Ticket, Fare, Cabin, Embarked]
Index: []

Так как не все классификаторы могут работать с категориальными признаками, в данном случае необходимо заменить их на числовые.

Также можно было бы выделить расширенные признаки, такие как статус пассажира (Mr., Mrs., Miss., Dr., Master. и т.д.), собственный индекс билета, индекс палубы и другие, но здесь ограничимся выбором более простых признаков.

### 1.5
В колонке Sex замените значения на 0, если пол "male", и на 1, если "female". В колонке Embarked замените параметры "U", "S", "C", "Q" на 0, 1, 2, 3 соответственно. Отбросьте колонки PassengerId, Name, Ticket, Cabin. Выведите первые 20 строк получившегося набора данных.

In [13]:
### YOUR CODE HERE ###

start_df = start_df.drop(['PassengerId', 'Name', 'Ticket', 'Cabin'], axis = 1)

In [14]:
import numpy as np

start_df['Sex'] = np.where(start_df.Sex == 'male', 0, np.where(start_df.Sex == 'female', 1, 255))
start_df['Embarked'] = np.where(start_df.Embarked == 'U', 0,
                  np.where(start_df.Embarked == 'S', 1,
                          np.where(start_df.Embarked == 'C', 2,
                                  np.where(start_df.Embarked == 'Q', 3, np.nan))))
start_df['Embarked'].fillna(start_df['Embarked'].mean(), inplace = True)

In [15]:
start_df.head(20)

Survived  Pclass  Sex   Age  SibSp  Parch     Fare  Embarked
0          0       3    0  22.0      1      0   7.2500       1.0
1          1       1    1  38.0      1      0  71.2833       2.0
2          1       3    1  26.0      0      0   7.9250       1.0
3          1       1    1  35.0      1      0  53.1000       1.0
4          0       3    0  35.0      0      0   8.0500       1.0
5          0       3    0  29.0      0      0   8.4583       3.0
6          0       1    0  54.0      0      0  51.8625       1.0
7          0       3    0   2.0      3      1  21.0750       1.0
8          1       3    1  27.0      0      2  11.1333       1.0
9          1       2    1  14.0      1      0  30.0708       2.0
10         1       3    1   4.0      1      1  16.7000       1.0
11         1       1    1  58.0      0      0  26.5500       1.0
12         0       3    0  20.0      0      0   8.0500       1.0
13         0       3    0  39.0      1      5  31.2750       1.0
14         0       3    1  14.0      0      0   7.8542       1.0
15         1       2    1  55.0      0      0  16.0000       1.0
16         0       3    0   2.0      4      1  29.1250       3.0
17         1       2    0  29.0      0      0  13.0000       1.0
18         0       3    1  31.0      1      0  18.0000       1.0
19         1       3    1  27.0      0      0   7.2250       2.0

### 1.6
Приступим к построению классификаторов. **Условимся, что, если функция или объект модели имеют параметр random_state, то устанавливаем его равным 17 в каждом из случаев.**

Разделите данные на тренировочный и тестовый датасеты, установив размер тестового как 0.25 (первая колонка Survived является целевой, поэтому необходимо сначала ее отделить от признаков).

In [16]:
from sklearn.model_selection import train_test_split 

In [17]:
### YOUR CODE HERE ###

X = start_df.drop(['Survived'], axis=1)
X_train, X_test, y_train, y_test = train_test_split(X, start_df.Survived, test_size=.25,  random_state = 17)

### 1.7
Обучите на полученных выборках несколько классификаторов, которые импортированы ниже.

**Примечание: в методе ближайших соседей используйте количество соседей, равное 5.**

In [18]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.tree import DecisionTreeClassifier
from sklearn.linear_model import LogisticRegression

In [19]:
### YOUR CODE HERE ###

KN = KNeighborsClassifier(n_neighbors=5).fit(X_train, y_train)
GNB = GaussianNB().fit(X_train, y_train)
DTC = DecisionTreeClassifier(random_state=17).fit(X_train, y_train)
LR = LogisticRegression(random_state=17).fit(X_train, y_train)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


Очевидно, в этом случае использовать метрику accuracy, которую мы применяли до этого, не совсем правильно: она не даст верную оценку классификатору, потому как выживших явно меньше, чем погибших.

Вспомним про такие метрики как точность и полнота. Здесь они подойдут хорошо, так как у нас имеются положительный и отрицательный классы, и определить корректно один из них может оказаться более важным .

### 1.8
В каждом из пунктов следующего теста выберите, что важнее максимизировать: точность (precision) или полноту (recall). Выпишите ответы.

1. Вероятность того, что при определенной поломке самолета он сможет долететь до пункта назначения (1 - долетел, 0 - не долетел).
2. Предсказание, представляет ли человек опасность, по анализу психического состояния (1 - представляет опасность, 0 - не представляет опасности).
3. Предсказание ухода клиента (1 - клиент ушел, 0 - остался).
4. Выявление рака на основе медицинских показателей (1 - болен раком, 0 - здоров).
5. Предсказание летальности при наблюдаемой мутации (1 - выживание, 0 - летальный исход).
6. Определение важности происшествия для экстренных служб (1 - важно, 0 - неважно).
7. Окупятся ли вложения в бизнес (1 - окупятся, 0 - не окупятся).

Ваш ответ:

1. Precision<br>
2. Recall<br>
3. Recall<br>
4. Recall<br>
5. Precision<br>
6. Recall<br>
7. Precision<br>

### 1.9
Определите, что важнее использовать в случае датасета Titanic: полноту или точность. Объясните, почему.

#### Для установления более точного числа потерь нужно снизить количество ложнопозитивных ответов. Поэтому важнее взять Precision, т.к. в формуле вычисления точности количество ложнопозитивных ответов стоит в знаменателе.

### 1.10
Для каждого классификатора выведите матрицу ошибок и самостоятельно рассчитайте метрику recall (расчеты должны присутствовать). Проверьте расчеты, воспользовавшись встроенной метрикой recall_score.

In [20]:
from sklearn.metrics import confusion_matrix, recall_score

In [21]:
### YOUR CODE HERE ###

KN_cnf_matrix = confusion_matrix(y_test, KN.predict(X_test))
GNB_cnf_matrix = confusion_matrix(y_test, GNB.predict(X_test))
DTC_cnf_matrix = confusion_matrix(y_test, DTC.predict(X_test))
LR_cnf_matrix = confusion_matrix(y_test, LR.predict(X_test))

In [22]:
KN_cnf_matrix

array([[110,  21],
       [ 47,  45]], dtype=int64)

In [23]:
GNB_cnf_matrix

array([[111,  20],
       [ 27,  65]], dtype=int64)

In [24]:
DTC_cnf_matrix

array([[112,  19],
       [ 26,  66]], dtype=int64)

In [25]:
LR_cnf_matrix

array([[114,  17],
       [ 29,  63]], dtype=int64)

In [26]:
KN_recall_calculated = KN_cnf_matrix[0,0] / (KN_cnf_matrix[0,0] + KN_cnf_matrix[1,0])
GNB_recall_calculated = GNB_cnf_matrix[0,0] / (GNB_cnf_matrix[0,0] + GNB_cnf_matrix[1,0])
DTC_recall_calculated = DTC_cnf_matrix[0,0] / (DTC_cnf_matrix[0,0] + DTC_cnf_matrix[1,0])
LR_recall_calculated = LR_cnf_matrix[0,0] / (LR_cnf_matrix[0,0] + LR_cnf_matrix[1,0])

In [27]:
KN_recall_builtin = recall_score(y_test, KN.predict(X_test))
GNB_recall_builtin = recall_score(y_test, GNB.predict(X_test))
DTC_recall_builtin = recall_score(y_test, DTC.predict(X_test))
LR_recall_builtin = recall_score(y_test, LR.predict(X_test))

In [28]:
print('Функция recall_score:\nKN_neighbours:   {}\nGaussianNB:  {}\nDecisionTree:  {}\nLogisticRegression:  {}'.format(KN_recall_builtin, GNB_recall_builtin, DTC_recall_builtin, LR_recall_builtin))

Функция recall_score:
KN_neighbours:   0.4891304347826087
GaussianNB:  0.7065217391304348
DecisionTree:  0.717391304347826
LogisticRegression:  0.6847826086956522


In [29]:
print('Расчет из матрицы ошибок:\nKN_neighbours:   {}\nGaussianNB:  {}\nDecisionTree:  {}\nLogisticRegression:  {}'.format(KN_recall_calculated, GNB_recall_calculated, DTC_recall_calculated, LR_recall_calculated))

Расчет из матрицы ошибок:
KN_neighbours:   0.7006369426751592
GaussianNB:  0.8043478260869565
DecisionTree:  0.8115942028985508
LogisticRegression:  0.7972027972027972


### 1.11
Выберите ту модель, на которой метрика recall давала лучший ответ, и рассчитайте для нее precision, используя встроенную функцию.

In [30]:
from sklearn.metrics import precision_score

In [31]:
### YOUR CODE HERE ###

precision_score(y_test, DTC.predict(X_test))

0.7764705882352941